trigger:
- main

pool:
  name: Default

jobs:
- job: Build
  workspace:
    clean: all
  steps:
  - script: |
      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      mvn clean package
    displayName: 'Maven Build'

  # - script: |
  #     cp ./webapp/target/*.war $(Build.ArtifactStagingDirectory)
  #   displayName: 'Copy .war file'

  # - task: PublishPipelineArtifact@1
  #   inputs:
  #     targetPath: '$(Build.ArtifactStagingDirectory)'
  #     artifact: 'drop'
  #   displayName: 'Publish .war file'
